import { clamp, dist } from "./utils";

export type JoystickDirection = "UP" | "UP_RIGHT" | "RIGHT" | "DOWN_RIGHT" | "DOWN" | "DOWN_LEFT" | "LEFT" | "UP_LEFT" | "NONE";

export interface JoystickData {
  /** Normalized X displacement [-1, 1] */
  x:         number;
  /** Normalized Y displacement [-1, 1] (Positive is UP, standard for game engines) */
  y:         number;
  /** Angle in radians (Cartesian standard: 0 is Right, PI/2 is Up) */
  angle:     number;
  /** Current drag distance in pixels (0 if within deadzone) */
  distance:  number;
  /** Normalized force [0, 1] proportional to maxRange (0 if within deadzone) */
  force:     number;
  /** 8-way directional output */
  direction: JoystickDirection;
}

export interface JoystickOptions {
  /** Physical limit in pixels the stick can move from the center. Default 50 */
  maxRange?: number;
  /** Callback executed when interaction starts */
  onStart?:  () => void;
  /** Continuous callback executed during drag */
  onMove?:   (data: JoystickData) => void;
  /** Callback executed when the stick is released */
  onEnd?:    () => void;
  /** "static" (fixed position) or "floating" (appears on click inside container). Default "static" */
  mode?:     "static" | "floating";
  /** Normalized deadzone threshold [0, 1]. Default 0.1 */
  deadzone?: number;
}

export class VirtualJoystick {

  public isDestroyed = false;
  public isDragging = false;
  public baseEl!:  HTMLDivElement;
  public stickEl!: HTMLDivElement;

  // Shared static instance for zero-alloc data emissions
  public joystickData: JoystickData = { x: 0, y: 0, angle: 0, distance: 0, force: 0, direction: "NONE" };

  private container:       HTMLElement;
  private maxRange:        number;
  private listenerTarget!: HTMLElement;

  private onStartCallback?: () => void;
  private onMoveCallback?:  (data: JoystickData) => void;
  private onEndCallback?:   () => void;

  private centerX = 0;
  private centerY = 0;
  private pointerId: number | null = null;
  private isAutoGeneratedDom = false;
  private mode:      "static" | "floating";
  private deadzone:  number;

  constructor(container: HTMLElement, options: JoystickOptions = {}) {
    this.container = container;
    this.maxRange = options.maxRange ?? 50;
    this.deadzone = options.deadzone ?? 0.1;
    this.mode = options.mode ?? "static";

    this.onStartCallback = options.onStart;
    this.onMoveCallback = options.onMove;
    this.onEndCallback = options.onEnd;

    this.buildDOM();
    this.initListeners();
  }

  private buildDOM(): void {
    if (typeof document === "undefined") return;

    // Check if the user already injected structured custom HTML
    const existingBase = this.container.querySelector(".affer-joystick-base") as HTMLDivElement;
    const existingStick = this.container.querySelector(".affer-joystick-stick") as HTMLDivElement;

    if (existingBase && existingStick) {
      this.baseEl = existingBase;
      this.stickEl = existingStick;
      this.isAutoGeneratedDom = false;
    } else {
      // Default semantic structure, free of visual CSS properties
      this.baseEl = document.createElement("div");
      this.baseEl.className = "affer-joystick-base";

      this.stickEl = document.createElement("div");
      this.stickEl.className = "affer-joystick-stick";

      this.baseEl.appendChild(this.stickEl);
      this.container.appendChild(this.baseEl);
      this.isAutoGeneratedDom = true;
      if (this.mode === "floating") this.baseEl.style.position = "fixed";
    }

    // Minimum structural styles required to prevent unwanted native behaviors
    const applyDefenses = (el: HTMLElement) => {
      el.style.touchAction = "none";
      el.style.userSelect = "none";
      el.style.webkitUserSelect = "none";
      (el.style as CSSStyleDeclaration & { webkitTouchCallout: string }).webkitTouchCallout = "none";
    };

    applyDefenses(this.container);
    applyDefenses(this.baseEl);
    applyDefenses(this.stickEl);
  }

  private initListeners(): void {
    if (typeof window === "undefined" || !this.baseEl) return;
    this.listenerTarget = this.mode === "floating" ? this.container : this.baseEl;
    this.listenerTarget.addEventListener("pointerdown", this.handlePointerDown, { passive: false });
    this.listenerTarget.addEventListener("pointermove", this.handlePointerMove, { passive: false });
    this.listenerTarget.addEventListener("pointerup", this.handlePointerUp, { passive: false });
    this.listenerTarget.addEventListener("pointercancel", this.handlePointerUp, { passive: false });
  }

  private removeListeners(): void {
    if (typeof window === "undefined" || !this.baseEl) return;
    this.listenerTarget = this.mode === "floating" ? this.container : this.baseEl;
    this.listenerTarget.removeEventListener("pointerdown", this.handlePointerDown);
    this.listenerTarget.removeEventListener("pointermove", this.handlePointerMove);
    this.listenerTarget.removeEventListener("pointerup", this.handlePointerUp);
    this.listenerTarget.removeEventListener("pointercancel", this.handlePointerUp);
  }

  /**
   * Recalculates the center coordinates of the joystick base.
   * Call this manually if the container moves or resizes while the joystick is active.
   * Only reliable in static mode. FLoating mode calibrates on pointerdown natively.
   */
  public recalibrate(): void {
    if (this.mode === "floating") return;
    const rect = this.baseEl.getBoundingClientRect();
    this.centerX = rect.left + rect.width / 2;
    this.centerY = rect.top + rect.height / 2;
  }

  /**
   * Utility to compute the 8-way direction of the stick based on Cartesian angle.
   */
  public getDirection(angle: number, force: number): JoystickDirection {
    if (force < this.deadzone) return "NONE"; // Dead zone

    let deg = angle * (180 / Math.PI);
    if (deg < 0) deg += 360;

    const index = Math.round(deg / 45) % 8;
    const directions = ["RIGHT", "UP_RIGHT", "UP", "UP_LEFT", "LEFT", "DOWN_LEFT", "DOWN", "DOWN_RIGHT"] as JoystickDirection[];
    return directions[index];
  }

  private handlePointerDown = (e: PointerEvent): void => {
    if (this.isDragging || this.isDestroyed) return;
    // Only intercept primary buttons
    if (e.pointerType === "mouse" && e.button !== 0) return;

    e.preventDefault();
    this.pointerId = e.pointerId;
    this.isDragging = true;

    if (this.mode === "floating") {
      const baseRect = this.baseEl.getBoundingClientRect();
      const offsetX = e.clientX - (baseRect.width / 2);
      const offsetY = e.clientY - (baseRect.height / 2);
      this.baseEl.style.transform = `translate3d(${offsetX}px, ${offsetY}px, 0)`;
      this.centerX = e.clientX;
      this.centerY = e.clientY;
    } else {
      this.recalibrate();
    }

    // Capture pointer ensures we receive 'pointermove' even if the finger leaves the DOM element bounds
    this.baseEl.setPointerCapture(this.pointerId);
    this.baseEl.setAttribute("data-active", "true");

    if (this.onStartCallback) this.onStartCallback();
  };

  private handlePointerMove = (e: PointerEvent): void => {
    if (!this.isDragging || e.pointerId !== this.pointerId) return;
    e.preventDefault();

    const dx = e.clientX - this.centerX;
    const dy = e.clientY - this.centerY;
    const distance = dist(0, 0, dx, dy);

    // Invert DY to align standard Cartesian math (0 = right, PI/2 = up)
    const angle = Math.atan2(-dy, dx);
    const clampedDistance = Math.min(distance, this.maxRange);
    const rawForce = clampedDistance / this.maxRange;

    // Use DOM axes (+Y is down) for visual transformation
    // Always responds, regardless of deadzone
    const moveX =  Math.cos(angle) * clampedDistance;
    const moveY = -Math.sin(angle) * clampedDistance;
    this.stickEl.style.transform = `translate3d(${moveX}px, ${moveY}px, 0)`;

    // Output mapped to Game Engine standard axes
    if (rawForce < this.deadzone) {
      this.joystickData.x = 0;
      this.joystickData.y = 0;
      this.joystickData.distance = 0;
      this.joystickData.force = 0;
      this.joystickData.direction = "NONE";
    } else {
      this.joystickData.x =  moveX / this.maxRange;
      this.joystickData.y = -moveY / this.maxRange;
      this.joystickData.distance = clampedDistance;
      this.joystickData.force = rawForce;
      this.joystickData.direction = this.getDirection(angle, this.joystickData.force);
    }

    this.joystickData.angle = angle; // Angle remains accurate as long as we are touching

    if (this.onMoveCallback) this.onMoveCallback(this.joystickData);
  };

  private handlePointerUp = (e: PointerEvent): void => {
    if (!this.isDragging || e.pointerId !== this.pointerId) return;
    e.preventDefault();

    this.isDragging = false;
    this.pointerId = null;
    try { this.baseEl.releasePointerCapture(e.pointerId); } catch {}

    // Controlled kinematic return to original mechanical center
    this.stickEl.style.transform = "translate3d(0px, 0px, 0)";

    // Reset data to prevent ghost inputs in the game loop
    this.joystickData.x = 0;
    this.joystickData.y = 0;
    this.joystickData.distance = 0;
    this.joystickData.force = 0;
    this.joystickData.direction = "NONE";
    // Angle remains un touched, as a resetting stick technically pointers nowhere,
    // but preserving the last angle is often useful for character facing directions.

    this.baseEl.setAttribute("data-active", "false");
    if (this.onEndCallback) this.onEndCallback();
  };

  /** Sets the deadzone threshold [0, 1]. */
  public setDeadzone(value: number) {
    if (value < 0 || value > 1) {
      console.warn(`Affer VirtualJoystick: Deadzone clamped to [0, 1]. Got ${value}.`);
    };
    this.deadzone = clamp(value, 0, 1);
  }

  /** Switches modes dynamically, safely rebinding event listeners. */
  public setMode(value: "static" | "floating") {
    if (this.mode === value) return;

    this.removeListeners();
    this.mode = value;

    if (this.isAutoGeneratedDom) this.baseEl.style.position = value === "floating" ? "fixed" : "";

    this.initListeners();
  }

  public destroy(): void {
    this.isDestroyed = true;
    this.removeListeners();

    // Zero out data to prevent ghost inputs if destroyed mid-drag
    this.joystickData.x = 0;
    this.joystickData.y = 0;
    this.joystickData.distance = 0;
    this.joystickData.force = 0;
    this.joystickData.direction = "NONE";
    this.isDragging = false;

    if (this.baseEl) this.baseEl.setAttribute("data-active", "false");
    if (this.isAutoGeneratedDom && this.baseEl) this.baseEl.remove();
  }

}

export default VirtualJoystick;
